### ISSUE TITLE
【提问】网络连接不上 ipfs.io 是否意味着就不能正常使用星火？

### ISSUE THREAD

**Issue by hujiharaka** [b3log/starfire#11]
中国移动宽带网络，电脑浏览器不能正常访问 ipfs.io ，试着翻墙之后可以访问，如果星火是依靠 ipfs.io 的网络服务来运行的话，那么用户不能接入 ipfs.io 网络，就不能使用星火了，对吗？还是说星火能通过中转服务器将用户提交的数据传送至 ipfs.io 的网络中永久保存？或者星火是否有离线运行的功能，在长时间网络受阻的情况下依然可以单机运行，待客户端有时机接入 ipfs.io 网络后能够一次性更新数据到 ipfs.io 网络中呢？

PS：码字不易，临到点击发布的时候在焦虑会不会因为网络的原因导致数据没有提交成功永久丢失了要重写一次，还是说发布之前的数据都会保存在本地不会因为网络的原因导致丢失找不回来？点击发布后网页中间的圈圈不停的转，这是提交成功的标志还是一直在提交中的标志，我是应该点浏览器的【退一步】还是【刷新】或者【关闭】呢，又要怎么验证发布的结果呢？

**Comment by hujiharaka** [comment]
重启了一次【ipfs daemon --enable-pubsub-experiment】之后倒是很快发布成功了，不知道之前一次发布数据丢失是不是因为在浏览器无痕模式下打开的缘故。
![starfire](https://user-images.githubusercontent.com/44595701/61171970-3cd69100-a5b1-11e9-8c43-a5e736ead609.PNG)

**Comment by 88250** [comment]
1. 星火使用 IPFS 私网机制进行组网，和官方的 ipfs.io 网关没有必然联系
2. IPFS 永久保存的机制是依赖本地节点的，或者说依赖网络里其他能够帮助保存的节点
3. 一些关于 IPFS 的基础知识请看这里 [IPFS 入门笔记](https://hacpai.com/article/1511015097370)
4. 浏览器无痕模式应该不影响发布，目前星火网络依赖 IPFS 发布订阅机制，使用的是 floodsub 模式

感谢你的参与和反馈。
